on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - name: Node [16.x]
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install NPM Packages
        working-directory: src
        run: |
          npm i
          npm i @angular/cli -g
      - name: Compile Angular app with Test config
        working-directory: src
        run: |
          ng build --configuration test --output-path ./test-published
      - name: Compile Angular app with Prod config
        working-directory: src
        run: |
          ng build --configuration production --output-path ./prod-published

      - name: Build versioned test image
        working-directory: src
        run: docker build . --file Dockerfile.test --tag nikneem/pollstar-app-test:${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Build latest test image
        working-directory: src
        run: docker build . --file Dockerfile.test --tag nikneem/pollstar-app-test:latest
      - name: Build versioned prod image
        working-directory: src
        run: docker build . --file Dockerfile --tag nikneem/pollstar-app:${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Build latest prod image
        working-directory: src
        run: docker build . --file Dockerfile --tag nikneem/pollstar-app:latest

      - name: Login to docker hub
        run: docker login -u nikneem -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push versioned image to docker
        run: docker push nikneem/pollstar-app-test:${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Push latest image to docker
        run: docker push nikneem/pollstar-app-test:latest
      - name: Push versioned image to docker
        run: docker push nikneem/pollstar-app:${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Push latest image to docker
        run: docker push nikneem/pollstar-app:latest

  publish-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile infrastructure
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az bicep build --file ./infrastructure/main.bicep
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bicep-templates
          path: infrastructure/*.json

  infrastructure-incremental-test:
    needs: [build, publish-bicep]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bicep-templates
          path: ./infrastructure
      - name: Azure Login
        uses: azure/login@v1.4.0
        with:
          creds: ${{ secrets.AZURE_TEST }}
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - name: Deploy Infrastructure
        id: arm
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az deployment sub create --name pollstar-front-end --location northeurope --template-file ./infrastructure/main.json --parameters ./infrastructure/params.test.json --parameters locationAbbreviation=neu --parameters containerVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}
