on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Node [16.x]
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install and npm run build
        working-directory: src
        run: |
          npm i
          npm i @angular/cli -g
      - name: Compile Angular app with Test config
        working-directory: src
        run: |
          ng build --configuration test --output-path ./test-published
      - name: Compile Angular app with Prod config
        working-directory: src
        run: |
          ng build --configuration production --output-path ./prod-published

      - name: Build versioned test image
        working-directory: src
        run: docker build . --file Dockerfile.test --tag nikneem/pollstar-app-test:${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Build latest test image
        working-directory: src
        run: docker build . --file Dockerfile.test --tag nikneem/pollstar-app-test:latest
      - name: Build versioned prod image
        working-directory: src
        run: docker build . --file Dockerfile --tag nikneem/pollstar-app:${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Build latest prod image
        working-directory: src
        run: docker build . --file Dockerfile --tag nikneem/pollstar-app:latest

      - name: Login to docker hub
        run: docker login -u nikneem -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push versioned image to docker
        run: docker push nikneem/pollstar-app-test:${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Push latest image to docker
        run: docker push nikneem/pollstar-app-test:latest
      - name: Push versioned image to docker
        run: docker push nikneem/pollstar-app:${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Push latest image to docker
        run: docker push nikneem/pollstar-app:latest
